### Wish List View
GET http://localhost:9000/api/wishlist HTTP/1.1


### Wish List ADD
POST http://localhost:9000/api/wishlist HTTP/1.1
Content-Type: application/json

{
    "id": 5007,
    "userId": 10002,
    "prodId": 4001
}
